### ISSUE TITLE
Metadata version mismatch

### ISSUE THREAD

**Issue by neerajnarayanan** [bfwg/ngx-drag-scroll#115]
i have updated ng2-dragscroll to ng-x dragscroll.but after updating i got the below errors.
ERROR in Error: Metadata version mismatch for module /home/neeraj/Desktop/InsuranextWeb/insuranext-web/insuranext-web/node_modules/ngx-drag-scroll/index.d.ts, found version 4, expected 3,resolving symbol AppModule in /home/neeraj/Desktop/InsuranextWeb/insuranext-web/insuranext-web/src/app/app.module.ts, resolving symbol AppModule in /home/neeraj/Desktop/InsuranextWeb/insuranext-web/insuranext-web/src/app/app.module.ts
    at Error (native)
    at syntaxError (/home/neeraj/Desktop/InsuranextWeb/insuranext-web/insuranext-web/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/home/neeraj/Desktop/InsuranextWeb/insuranext-web/insuranext-web/node_modules/@angular/compiler/bundles/compiler.umd.js:24979:23)
    at StaticReflector.simplify (/home/neeraj/Desktop/InsuranextWeb/insuranext-web/insuranext-web/node_modules/@angular/compiler/bundles/compiler.umd.js:24991:13)
    at StaticReflector.annotations (/home/neeraj/Desktop/InsuranextWeb/insuranext-web/insuranext-web/node_modules/@angular/compiler/bundles/compiler.umd.js:24418:41)
    at _getNgModuleMetadata (/home/neeraj/Desktop/InsuranextWeb/insuranext-web/insuranext-web/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/home/neeraj/Desktop/InsuranextWeb/insuranext-web/insuranext-web/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (/home/neeraj/Desktop/InsuranextWeb/insuranext-web/insuranext-web/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/home/neeraj/Desktop/InsuranextWeb/insuranext-web/insuranext-web/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/home/neeraj/Desktop/InsuranextWeb/insuranext-web/insuranext-web/node_modules/@ngtools/webpack/src/plugin.js:241:66)
    at _donePromise.Promise.resolve.then.then.then.then.then (/home/neeraj/Desktop/InsuranextWeb/insuranext-web/insuranext-web/node_modules/@ngtools/webpack/src/plugin.js:495:24)
    at process._tickCallback (internal/process/next_tick.js:103:7)

Angular cli version is as follows
Angular CLI: 1.5.3
Node: 6.10.0
OS: linux x64
Angular: 4.4.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, tsc-wrapped

@angular/cdk: 2.0.0-beta.11
@angular/cli: 1.5.3
@angular/material: 2.0.0-beta.11
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.21
@angular-devkit/schematics: 0.0.37
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.3
@schematics/angular: 0.1.7
typescript: 2.3.4
webpack: 3.7.1

**Comment by akkumar** [comment]
The project needs ng5+ .

**Comment by bfwg** [comment]
Should we put the ng5+ requirement in the README.md?

**Comment by akkumar** [comment]
@bfwg - Good idea. That should definitely help.

**Comment by akkumar** [comment]
#116 adds the requirement explicitly
