### ISSUE TITLE
getComputedStyle on SSR Universal

### ISSUE THREAD

**Issue by gvestit** [bfwg/ngx-drag-scroll#314]
* **I'm submitting a ...**
  - [ X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
When we are rendering on server side the component which is using this library we are getting the error "ReferenceError: getComputedStyle is not defined" onserver side.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**  you can use the demo site as an example or via https://plnkr.co

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

ReferenceError: getComputedStyle is not defined
3|main  |     at DragScrollComponent.ngAfterViewInit (server/447.js:1:41636)
3|main  |     at callHook (server/main.js:1:2487534)
3|main  |     at callHooks (server/main.js:1:2487151)
3|main  |     at executeInitAndCheckHooks (server/main.js:1:2486487)
3|main  |     at refreshView (server/main.js:1:2630872)
3|main  |     at refreshComponent (server/main.js:1:2648689)
3|main  |     at refreshChildComponents (server/main.js:1:2626715)
3|main  |     at refreshView (server/main.js:1:2630553)
3|main  |     at refreshEmbeddedViews (server/main.js:1:2647970)
3|main  |     at refreshView (server/main.js:1:2630083)

**Comment by quedicesebas** [comment]
With SSR?

**Comment by apappas1129** [comment]
Probably just have to wrap everything in `ngAfterViewInit` [here](https://github.com/bfwg/ngx-drag-scroll/blob/d364710fcc06b17bd4eb0a34e4637362ab084d59/projects/ngx-drag-scroll/src/lib/ngx-drag-scroll.component.ts#L282) with [`afterNextRender`](https://v17.angular.io/api/core/afterNextRender).

**Comment by Malhar-Naliyapara** [comment]
October 2024, Still facing issue using SSR. Can not get the getComputedStyle as can not get window in SSR. Any update on that ?

**Comment by apappas1129** [comment]
> October 2024, Still facing issue using SSR. Can not get the getComputedStyle as can not get window in SSR. Any update on that ?

Can you provide the error message with what line of code it is referring to? For example, I think the `window` access is handled properly here:

https://github.com/bfwg/ngx-drag-scroll/blob/d364710fcc06b17bd4eb0a34e4637362ab084d59/projects/ngx-drag-scroll/src/lib/ngx-drag-scroll.component.ts#L291

**Comment by ttamas1105-tamas** [comment]
> > October 2024, Still facing issue using SSR. Can not get the getComputedStyle as can not get window in SSR. Any update on that ?
> 
> Can you provide the error message with what line of code it is referring to? For example, I think the `window` access is handled properly here:
> 
> [ngx-drag-scroll/projects/ngx-drag-scroll/src/lib/ngx-drag-scroll.component.ts](https://github.com/bfwg/ngx-drag-scroll/blob/d364710fcc06b17bd4eb0a34e4637362ab084d59/projects/ngx-drag-scroll/src/lib/ngx-drag-scroll.component.ts#L291)
> 
> Line 291 in [d364710](/bfwg/ngx-drag-scroll/commit/d364710fcc06b17bd4eb0a34e4637362ab084d59)
> 
>  typeof window !== 'undefined'

The issue is here on line 346:

    this.rtl =
      getComputedStyle(this._contentRef.nativeElement).getPropertyValue(
        'direction'
      ) === 'rtl';
